import { EResult } from "@/types/HelperEnums/EResult";
import { EGender } from "@/types/HelperEnums/EGender";
import { BaseEngine } from "./BaseEngine";

export default class HeadacheEngine extends BaseEngine {
  constructor(gender: EGender, age: number) {
    super("peavalu", gender, age, [
      {
        contentEst: "korduv peavalu",
        result: EResult.FamilyDoctor,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "korduv mõõduka tugevusega peavalu",
        result: EResult.FamilyDoctor,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "näopiirkonna valu sh hambavalu ilma kõrge palavikuta",
        result: EResult.FamilyDoctor,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "migreen",
        result: EResult.FamilyDoctor,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "külmetushaigusest tulenev peavalu",
        result: EResult.FamilyDoctor,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "peavalu mis allub ravile",
        result: EResult.FamilyDoctor,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "äkki (sekund, minuti jooksul) tekkinud valu peas",
        result: EResult.EmergencyRoom,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "peavalu koos minestusega",
        result: EResult.EmergencyRoom,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "täielik nägemiskaotus",
        result: EResult.EmergencyRoom,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "tugev silmavalu, katsudes on silmamuna kõva",
        result: EResult.EmergencyRoom,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "verevalumitega nahalööbe",
        result: EResult.EmergencyRoom,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "peatrauma",
        result: EResult.EmergencyRoom,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "tugev migreenihoog",
        result: EResult.EmergencyRoom,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "hiljutine nägemislangus",
        result: EResult.EmergencyRoom,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "korduv oksendamine 24 tunni jooksul",
        result: EResult.EmergencyRoom,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "palavik on üle 38 kraadi, mis ei allu ravile",
        result: EResult.EmergencyRoom,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
      {
        contentEst: "tugev peavalu eakal",
        result: EResult.EmergencyRoom,
        contentEng: null,
        gender: EGender.any,
        minAge: null,
        maxAge: null,
      },
    ]);
  }
}
